version: 0.0
os: linux
build:
        commands:
          - echo Entering build phase...
          - echo Build started on `date`
          - mvn clean package
            timeout: 300
#files: 
#  - source: /home/ec2-user/Maven-Web-Project/target/maven-web-project-1.1-SNAPSHOT.war
#  - destination: /home/ec2-user/apache-tomcat-8.5.40/webapps
post_build:
        commands:
          - echo Entering post_build phase...
          - echo Build completed on `date`
          - mv /home/ec2-user/Maven-Web-Project/target/maven-web-project-1.1-SNAPSHOT.war /home/ec2-user/apache-tomcat-8.5.40/webapps




#files:
 # - source: /target/SampleMavenTomcatApp.war
  #   destination: /tmp/codedeploy-deployment-staging-area/
#   - source: /scripts/configure_http_port.xsl
   #  destination: /tmp/codedeploy-deployment-staging-area/
# hooks:
 #  ApplicationStop:
   #  - location: scripts/stop_application
     #  timeout: 300
  # BeforeInstall:
   #  - location: scripts/install_dependencies
     #  timeout: 300
  # ApplicationStart:
   #  - location: scripts/write_codedeploy_config.sh
    # - location: scripts/start_application
      # timeout: 300
 #  ValidateService:
   #  - location: scripts/basic_health_check.sh
