version: 0.2

phases:
  post_build:
    commands:
      - mvn package
      - mv target/maven-web-project-1.1-SNAPSHOT.war  maven-web-project-1.1-SNAPSHOT.war
artifacts:
  files:
    - source: /target/maven-web-project-1.1-SNAPSHOT.war
      destination: /home/ec2-user/apache-tomcat-8.5.40/webapps
    - maven-web-project-1.1-SNAPSHOT.war
    - .ebextensions/**/*




#files:
 # - source: /target/SampleMavenTomcatApp.war
  #   destination: /tmp/codedeploy-deployment-staging-area/
#   - source: /scripts/configure_http_port.xsl
   #  destination: /tmp/codedeploy-deployment-staging-area/
# hooks:
 #  ApplicationStop:
   #  - location: scripts/stop_application
     #  timeout: 300
  # BeforeInstall:
   #  - location: scripts/install_dependencies
     #  timeout: 300
  # ApplicationStart:
   #  - location: scripts/write_codedeploy_config.sh
    # - location: scripts/start_application
      # timeout: 300
 #  ValidateService:
   #  - location: scripts/basic_health_check.sh
